import type { Metadata } from "next";
import localFont from "next/font/local";
import {Navbar} from "./Components/ui"
import "./globals.css";
import { Footer} from "./Components/ui";
import { Toaster } from "sonner";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >

        <Navbar />
        <Toaster rich-colors position="top-right" />
        <main className="px-4">
        {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
